### ISSUE TITLE
Text in code block has a white background

### ISSUE THREAD

**Issue by plagov** [Mitrichius/hugo-theme-anubis#119]
The text in the code block has a white background that makes it impossible to read. For example:
![Screenshot from 2021-12-01 23-10-17](https://user-images.githubusercontent.com/16601852/144314500-e1b5be02-f505-4633-bac0-b7d8cab3b30d.png)
I don't use any custom style. Probably, related to this change - https://github.com/Mitrichius/hugo-theme-anubis/issues/117
Could you please help with it?
The source - https://github.com/plagov/blog
The end result - https://plagov.github.io/posts/2021-12-01-rule-engine-pattern/

**Comment by Mitrichius** [comment]
Sorry for this. Should be fixed now.

**Comment by plagov** [comment]
@Mitrichius thanks! It's fine now if the code block is wrapped with just backticks. But it is still the same if I specify the language inside the code block. For example:

![image](https://user-images.githubusercontent.com/16601852/144490978-f6d374af-aa01-4333-afae-bb47467c8a02.png)

**Comment by Mitrichius** [comment]
I don't see fix on your site. Built it locally from your source and looks fine
<img width="929" alt="dark" src="https://user-images.githubusercontent.com/7609386/144559338-6ae3d34f-6300-4ac9-aea6-c9468f03da87.png">
<img width="915" alt="light" src="https://user-images.githubusercontent.com/7609386/144559343-de58d6f5-9c88-4a76-b8ac-7272f9bceb02.png">

**Comment by plagov** [comment]
@Mitrichius I had to update git submodules when deploying to GitHub pages with GitHub Actions. I thought that this command does it - `git submodule update --init --recursive`, but it didn't. So, had to run some commands and now it works. Thank you for your help! I will have to figure it out how to update submodules to the latest commit on `master` or to a specific tag.
